spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9103}
  datasource:
    url: jdbc:mysql://${MYSQL_HOMEWORK_HOST:localhost}:${MYSQL_HOMEWORK_PORT:3309}/${MYSQL_HOMEWORK_DB:assistudy_homework}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_DB_USER:assistudy}
    password: ${MYSQL_DB_PASSWORD:assistudy}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:eureka@localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.assistudy: DEBUG
    org.hibernate.SQL: DEBUG
