spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: jdbc:mysql://${MYSQL_HOMEWORK_HOST}:${MYSQL_HOMEWORK_PORT}/${MYSQL_HOMEWORK_DB}?useSSL=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  cloud:
    inetutils:
      preferred-networks:
        - 10.20

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    root: INFO
    com.assistudy: INFO
